[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
